### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by dxp10** [xwillxu/xwillxu#2]
Hi friend, could you rate my repositories and I'll rate yours at the same time? Thanks!

**Comment by xwillxu** [comment]
We will just rate the READMEs ok.

**Comment by xwillxu** [comment]
Yours would be a 8/10

**Comment by dxp10** [comment]
Thanks

**Comment by xwillxu** [comment]
bro when are you going to rate mine

**Comment by dxp10** [comment]
I liked your Readme too. Especially the detailed statistics
